name: Lighthouse CI Test
on: 
  push:
    branches:
      - main

jobs: 
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      
      - name: Install packages
        run: yarn install 

      - name: Build
        run: yarn build

      - name: Preview
        run: yarn preview --port 3000

      - name: Netstat
        run: netstat -nltp | grep 3000

      - name: Lighthouse CI
        run: yarn dlx @lhci/cli autorun
